services:
  - type: web
    name: project-manager-laravel
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Project Manager
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: FRONTEND_URL
        value: https://taskflowprojectmanager.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://taskflowprojectmanager.vercel.app
      - key: CORS_SUPPORTS_CREDENTIALS
        value: true
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: project-manager-db
          property: connectionString
      - key: DB_SSLMODE
        value: require
      - key: CACHE_STORE
        value: database
      - key: DASHBOARD_CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: true

databases:
  - name: project-manager-db
    plan: free
    databaseName: project_manager
    user: project_manager
